### ISSUE TITLE
Object Hierarchy import failing in preprocessing

### ISSUE THREAD

**Issue by meganforbes** [collectionspace/collectionspace-csv-importer#109]
- Created file based on template
- Uploaded to CSV Importer
- Preprocessing failed with messages:
     * Fields that will import: 0 of 3
     * Fields that will not import: narrower_object_number; broader_object_number; relationship_type
     * Required field missing: objectnumber must be present

CSV filed tried to import attached.

[Book4.csv](https://github.com/collectionspace/collectionspace-csv-importer/files/7092219/Book4.csv)

**Comment by kspurgin** [comment]
Looks like you are using the collectionobject mapper on [this job](https://importer.collectionspace.org/batches/244/step/preprocesses/new).

You need to use the objecthierarchy mapper for this. If that fails, please open a new ticket!

**Comment by meganforbes** [comment]
Duh.

**Comment by meganforbes** [comment]
Well, still having issues. I deleted my Core Dev connection and established a new one for v7. I re-ran the job (called Hierarchy Test Dev 3) and received the attached report.

[hierarchy-test-dev-3-20210902-1320_processing_report.csv](https://github.com/collectionspace/collectionspace-csv-importer/files/7099212/hierarchy-test-dev-3-20210902-1320_processing_report.csv)

**Comment by kspurgin** [comment]
As this is something completely separate... and complicated... I'm going to make a new issue for it.

**Comment by kspurgin** [comment]
As a side note, you can change the version in your existing connection so you don't have to delete and create a new connection.
