### ISSUE TITLE
Object Hierarchy failing in processing step

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/collectionspace-csv-importer#110]
@meganforbes got the following mapping errors in the processing step on Core Dev 7.0 with object hierarchy mapper. 

https://github.com/collectionspace/collectionspace-csv-importer/files/7099212/hierarchy-test-dev-3-20210902-1320_processing_report.csv

The error received from `collectionspace-mapper` is: 

```
List request failed: org.nuxeo.ecm.core.query.QueryParseException: Failed to execute query: SELECT * FROM Relation WHERE collectionspace_core:tenantId = '1' AND ((ecm:currentLifeCycleState <> 'deleted' AND ecm:currentLifeCycleState <> 'locked_deleted' AND ecm:currentLifeCycleState <> 'replicated_deleted') AND relations_common:subjectCsid = 'urn:cspace:core.collectionspace.org:collectionobjects:id(16161bff-b01a-4b55-95aa)'Hierarchy Test 0001'' AND relations_common:objectCsid = 'urn:cspace:core.collectionspace.org:collectionobjects:id(34bb1c08-5f46-4347-94db)'Hierarchy Object Parent Record'') AND ecm:isProxy = 0 AND ecm:isCheckedInVersion = 0 ORDER BY collectionspace_core:updatedAt DESC, Syntax error: Invalid token <Hierarchy> at offset 333 -- /app/vendor/bundle/ruby/2.7.0/bundler/gems/collectionspace-mapper-ff839d011340/lib/collectionspace/mapper/tools/record_status_service.rb:74:in `count_results'
```

Both the parent and child record referenced in the error message still exist as normal object records in the system.

**Comment by kspurgin** [comment]
Well that's an error I haven't seen before, and it is interesting in a bad way. This, combined with collectionspace/collectionspace-mapper#123 are a pattern starting to suggest something may have changed in the API and how it interacts with Nuxeo under the hood. Or in how the API responses are formatted. This is not a part of the stack I've worked with a lot. This may require some changes to how the cspace-client formulates queries or handles results. 

Let me dig into it...

**Comment by kspurgin** [comment]
I do think this and collectionspace/collectionspace-mapper#123 are caused by the same underlying issue. I will be noting progress/etc on my work on the underlying issue over there. 

I'm leaving this open because once the underlying issue is fixed, there are number of pieces that need to be updated to get the fixes into the csv-importer. Once it is all done, this ticket should be closed

**Comment by kspurgin** [comment]
So I was wrong about this being the same underlying issue as collectionspace/collectionspace-mapper#123. I can no longer duplicate that one anywhere, and I get the same errors for this one on my local dev environment, so back to treating this as its own thing. 

It does not appear that there were any meaningful changes to the client/API, either, so back to the debugging drawing board on this one.

**Comment by kspurgin** [comment]
Finally found it. The mapper is building the query with the subject/object Objects' refnames, not their CSIDs.

I am going to add an easily testable/reusable "search_relation" method to collectionspace-client, then incorporate that into collectionspace-mapper.

**Comment by kspurgin** [comment]
Then I couldn't repeat the issue testing the mapper directly. 

I FINALLY just determined that the object number is not cached when I test the mapper directly, but it *is* cached at this point when run through the importer tool.

So [this line](https://github.com/collectionspace/collectionspace-mapper/blob/ff839d0113401bc3c724d73b46ecd025e2fc6d11/lib/collectionspace/mapper/term_searchable.rb#L46) is returning the refname in the importer tool, and nil in the mapper outside the context of the importer. 

So now I actually know what to fix

**Comment by kspurgin** [comment]
The fix is to extract the CSID from the refname URN when it is returned from the cache

**Comment by kspurgin** [comment]
Not closed until importer is updated and redeployed!

**Comment by mark-cooper** [comment]
@kspurgin deployed!
