### ISSUE TITLE
Greater than 100 percent completion

### ISSUE THREAD

**Issue by meganforbes** [collectionspace/collectionspace-csv-importer#135]
Probably not a pressing issue, but just ran a batch that wrapped up at 107% complete. There were several duplicate entry warnings that I was aware of / ignored. I left the batch in there, it's called Outreach Concepts 1. All the data appears to have transferred properly.

![image](https://user-images.githubusercontent.com/6516857/140093139-80acc761-50dd-4527-b9cb-face9430a487.png)

**Comment by kspurgin** [comment]
It's because the file size is 666 bytes. Clearly it has a demon. 🤘

Just kidding. I wrote this part, so I'll steal it from Mark.
