### ISSUE TITLE
Changing a new user's permission level/groups also changes their password

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/collectionspace-csv-importer#185]
I think we had this problem before and I thought it got fixed, but this just happened: 

- Jessi signed up for an account
- I logged in as admin, went into her user, set her level to "Manager" and added her to the TB4YB group, saved. 
- Then in the user list I realized I needed to enable her, so I checked that box. 

After I did those things, she could no longer log in. 

I went back into her user page, entered a new password for her and saved

She was able to log in using that password.

It is non-intuitive to me to have the password be changed/updated when those fields were not updated. Is it getting confused about the actual values in those fields vs. what the UI puts in them for **display** when that page is loaded?

**Comment by mark-cooper** [comment]
@kspurgin so far I haven't been able to replicate this online or locally. I went through the steps using my email address (twice over), and everything was ok. I'm leaning towards thinking the original signup password wasn't being input correctly 🤷‍♂️
