### ISSUE TITLE
Preprocessing step fails at 99% when extra blank line on end of CSV

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/collectionspace-csv-importer#213]
Reported by OMCA

[sample.csv](https://github.com/user-attachments/files/15516744/sample.csv)

or:
```
objectnumber,objectcount
A67,1
A68,2^M
```
We can surely do something more graceful than this, but should at least say what the problem is. 

We might already be capturing what the problem is---one error is counted, which is why it's showing as a failure---but no error message is displayed: 
![image](https://github.com/collectionspace/collectionspace-csv-importer/assets/450570/ca03cc07-06ec-493a-b31a-8915a1982ca4)

**Comment by mark-cooper** [comment]
Line endings:

```bash
# download IP Audit_ Copyright OMCA - Copy of ipaudit.Copyright_OMCA (1)_1.csv as ip.csv
cat -e ip.csv
# truncated output
^M$
^M
```

Read with:

```ruby
#!/usr/bin/env/ruby
require "csv"

csv = CSV.open("ip.csv", headers: true, encoding: 'bom|utf-8', nil_value: '')
loop do
  row = csv.shift
  puts row.to_s
  break unless row
rescue CSV::MalformedCSVError => e
  puts e.message
end
```

Error:

```txt
Unquoted fields do not allow new line <"\r"> in line 9044.
```
