### ISSUE TITLE
% Complete shows > 100% when transferring non-hierarchical relations

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/collectionspace-csv-importer#22]
Calculation of "% Complete" is based on number of rows in original spreadsheet.

Under the hood, each row in a non-hierarchical relationship CSV is turned into 2 records that must be transferred. So for a 100 row spreadsheet, 200 records get transferred.

I'm not messing with this now, as we have an issue in the CSpace app to make the application handle creating the reciprocal record. But since I don't know a timeframe for the app being able to handle this, I wanted to note this known issue.

**Comment by mark-cooper** [comment]
@kspurgin do you want me to take a look into this one or were you planning on doing it?

**Comment by kspurgin** [comment]
I was planning to take care of it at some point
