### ISSUE TITLE
Update Text on Batch Process Pages

### ISSUE THREAD

**Issue by meganforbes** [collectionspace/collectionspace-csv-importer#63]
In a better world, I know how to do PRs. In this world, here are text files with the changes.

[Batch process field names.txt](https://github.com/collectionspace/cspace-batch-import/files/6459051/Batch.process.field.names.txt)

[Batch process preprocess steps.txt](https://github.com/collectionspace/cspace-batch-import/files/6459212/Batch.process.preprocess.steps.txt)

[Batch import process steps.txt](https://github.com/collectionspace/cspace-batch-import/files/6460180/Batch.import.process.steps.txt)

**Comment by kspurgin** [comment]
Sorry it has taken FOREVER to get to this. 

Is there a link you want to put in where it says "View the Complete Documentation"?

<img width="685" alt="image" src="https://user-images.githubusercontent.com/450570/123817721-6421e800-d8c6-11eb-9606-19cd8e0af963.png">

**Comment by kspurgin** [comment]
![image](https://user-images.githubusercontent.com/450570/123819435-c5968680-d8c7-11eb-8daa-08557c75e918.png)

**Comment by meganforbes** [comment]
Link for complete documentation: https://collectionspace.atlassian.net/wiki/spaces/COL/pages/2271936513/User+Manual+CollectionSpace+CSV+Importer
