### ISSUE TITLE
Handle mapper manifests from multiple releases

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/collectionspace-csv-importer#91]
Depends on collectionspace/cspace-config-untangler#72

See that issue for some architecture decision-ish explanation of why. 

In the future, we may ever restructure the way mappers are referenced/organized/stored to minimize redundant storage of mappers that are identical except for version number. But that's a lot more work and the mapper files are small.

**Comment by kspurgin** [comment]
@mark-cooper - there is a 7.0 dev manifest over [here](https://github.com/collectionspace/cspace-config-untangler/tree/main/data/mapper_manifests) for testing

**Comment by kspurgin** [comment]
A couple notes about other little things I was going to change related to this, before I throw my branch away.

In `config/locales/en.yml` I changed `url_link_prefix` from "Configuration" to "Active mapper manifest(s)". Elsewhere we are referring to these as mapper manifests so I was aiming to make language more consistent. 

I was also updating `docs/managing_mappers.adoc` which needed only a minor tweak before, but might need more revision given the new approach.

**Comment by mark-cooper** [comment]
Was done: https://github.com/collectionspace/collectionspace-csv-importer/pull/94
